name: Make distribution binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-latest
    name: macOS
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: '3.x'
      - name: Install pyinstaller
        run: |
          pip3 install certifi pyinstaller
      - name: Make binary
        run: |
          pyinstaller --onefile --add-data "Darwin/*:Darwin" --add-data "icon.ico:icon.ico" --add-data "i18n/*:i18n" --target-architecture universal2 TWLMagician.py
          cd dist
          zip -r ../TWLMagician-macOS.zip TWLMagician
      - name: Publish artifact
        uses: actions/upload-artifact@main
        with:
          path: TWLMagician-macOS.zip
          name: macos

  Linux:
    runs-on: ubuntu-latest
    name: Linux
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Make binary
        run: |
          zip TWLMagician-Python3-Linux.zip TWLMagician.py appgen.py pyutils.py
          zip -ur TWLMagician-Python3-Linux.zip Linux py_langs tk_tooltip i18n
      - name: Publish artifact
        uses: actions/upload-artifact@main
        with:
          path: TWLMagician-Python3-Linux.zip
          name: Linux
